name: node js ci

on:
  - push
jobs:
  node-js-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node-js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup project
        run: make setup

      - name: Run linter
        run: make lint

      - name: Run tests
        run: make test
